### ISSUE TITLE
Modal

### ISSUE THREAD

**Issue by brissebrat** [Greg-Klein/map-component#2]
Propositions de modifs :
- Ajouter ça au constructeur (swal) : customClass: "custom-map-modal"
- Afficher un texte plutôt que l'url (en plus de url, pouvoir passer urlLabel. Par défaut : 'More...' ?)

**Comment by Greg-Klein** [comment]
Mis en place dans la [release 1.0.2](https://github.com/Greg-Klein/map-component/releases/tag/1.0.2)
