### ISSUE TITLE
Polygon

### ISSUE THREAD

**Issue by brissebrat** [Greg-Klein/map-component#4]
Modifier le style pour prendre en compte les Polygon :

style: function(feature, resolution){
            var geoName = feature.getGeometry().getType();
            var props = feature.getProperties();
           
            var color = props.color;
            if (color == null){
              color = 'red';
            }
                               
            if (geoName == 'Point'){
          
            var icon = props.icon;
            if (icon == null){
              icon = '\uf041';
            }
          
            var font = props.font;
            if (font == null){
              font = 'FontAwesome';
            }

            return [new ol.style.Style({
              text: new ol.style.Text({
                font: 'normal 24px ' + font,
                text: icon,
                textBaseline: 'Bottom',
                fill: new ol.style.Fill({
                  color: color
                })
              })
            })];
            }else if (geoName == 'Polygon'){
                return [new ol.style.Style({
                    stroke: new ol.style.Stroke({
                        color: color,
                        width: 2
                      })
                  })];
            }
          }

**Comment by brissebrat** [comment]
Et aussi des lignes :

else if (geoName == 'LineString'){
            	return [new ol.style.Style({
                    stroke: new ol.style.Stroke({
                        color: color,
                        width: 1
                      })
                  })];
            }

**Comment by Greg-Klein** [comment]
Mis en place dans la [release 1.0.2](https://github.com/Greg-Klein/map-component/releases/tag/1.0.2)
