### ISSUE TITLE
GeometryCollection

### ISSUE THREAD

**Issue by brissebrat** [Greg-Klein/map-component#6]
Pour l'affichage des GeometryCollection :

styles.GeometryCollection = [new ol.style.Style({
            stroke: new ol.style.Stroke({
              color: color,
              width: 1
            }), text: new ol.style.Text({
                font: 'normal 24px ' + font,
                text: icon,
                textBaseline: 'Bottom',
                fill: new ol.style.Fill({
                  color: color
                })
              })
          })];

**Comment by Greg-Klein** [comment]
Ajouté dans la [release 1.0.4](https://github.com/Greg-Klein/map-component/releases/tag/1.0.4)
